name = "rto-firewall"
main = "src/index.ts"
compatibility_date = "2025-07-10"
compatibility_flags = ["nodejs_compat"]

observability = { enabled = true }

kv_namespaces = [
  { binding = "RTO_DATA", id = "52c9b3f2642f4b6db85042b4f14995c2", preview_id = "52c9b3f2642f4b6db85042b4f14995c2" }
]

[vars]
RISK_THRESHOLD = "75"
PREPAID_DISCOUNT_PERCENT = "10"
NATIONAL_RTO_AVERAGE = "0.15"
